services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "80:5000"
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      PYTHONPATH: /app/src

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: auth_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "mysql-db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
